### ISSUE TITLE
Output when "--bin-size" is changed

### ISSUE THREAD

**Issue by shirotak** [KolmogorovLab/Wakhan#8]
Thank you for your developing such a great tool.  
When I set --bin-size=10000, calculation was completed without error, but the output looks wrong.  
I would appreciate it if you could make adjustments to obtain the correct output.  
Thank you in advance!
<img width="759" alt="Screenshot 2024-05-01 at 12 02 23 PM" src="https://github.com/KolmogorovLab/Wakhan/assets/38811912/e51d3765-dfe5-4077-8498-c6cc41b75ef8">

![newplot (6)](https://github.com/KolmogorovLab/Wakhan/assets/38811912/fa61397a-a710-46de-bb97-4db9cea04b29)
![newplot (7)](https://github.com/KolmogorovLab/Wakhan/assets/38811912/0541edcb-bc0b-4cd2-a5ed-acddf1948ae2)
...
![newplot (8)](https://github.com/KolmogorovLab/Wakhan/assets/38811912/b167481e-d3c9-4623-8047-f4fd5d76a4eb)
![newplot (9)](https://github.com/KolmogorovLab/Wakhan/assets/38811912/6b6c611e-32c7-41d7-b47a-45180b6502d1)
![newplot (10)](https://github.com/KolmogorovLab/Wakhan/assets/38811912/e8aacc19-783f-4f24-a61b-ee5c9e820b85)
![newplot (11)](https://github.com/KolmogorovLab/Wakhan/assets/38811912/446d19bc-725f-41d8-94c1-9da81218c86a)
![newplot (12)](https://github.com/KolmogorovLab/Wakhan/assets/38811912/a0927cb2-2109-4bee-9308-683080f51006)
![newplot (13)](https://github.com/KolmogorovLab/Wakhan/assets/38811912/61c49993-b416-4670-9aa4-ddd6d60d3bc9)

**Comment by tahashmi** [comment]
Sorry for this, can you please follow [this](https://github.com/KolmogorovLab/Wakhan/tree/main?tab=readme-ov-file#note) step to copy the coverage data and then update the code and rerun to check if it's fixed? Also since 1395 has too much noise in coverage, better to [use](https://github.com/KolmogorovLab/Wakhan?tab=readme-ov-file#known-issue) this parameter.
